/* GENERATED by build_weather_satellite.py - do not edit.
   When each region's satellite composite was photographed. */
window.WXSAT = {"colorado":{"from":"2026-08-18","to":"2026-09-12","exact":false,"days":26},"chesapeake":{"from":"2026-08-18","to":"2026-09-12","exact":false,"days":26},"salish":{"from":"2026-08-18","to":"2026-09-12","exact":false,"days":26}};
